services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '8081:80'      # 使用8081端口
      - '8443:443'     # 使用8443端口
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../../out/renderer:/usr/share/nginx/html
      - ./logs:/var/log/nginx
    restart: always
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      - default

networks:
  default:
    enable_ipv6: true
    driver: bridge
    ipam:
      config:
        - subnet: '2001:db8:1::/64'
